/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class miku_lib_common_Native_NativeUtil */

#ifndef _Included_org_neocities_a3441veryonline_obliteratingsword_UnsafeUtil
#define _Included_org_neocities_a3441veryonline_obliteratingsword_UnsafeUtil
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_neocities_a3441veryonline_obliteratingsword_UnsafeUtil
 * Method:    sizeof
 * Signature: Ljava/lang/Object;
 */
JNIEXPORT jclass JNICALL Java_org_neocities_a3441veryonline_obliteratingsword_UnsafeUtil_sizeof
  (JNIEnv *, jobject);

/*
 * Class:     org_neocities_a3441veryonline_obliteratingsword_UnsafeUtil
 * Method:    malloc
 * Signature: Ljava/lang/Object;
 */
JNIEXPORT void JNICALL Java_org_neocities_a3441veryonline_obliteratingsword_UnsafeUtil_malloc
  (JNIEnv *, jint);

/*
 * Class:     org_neocities_a3441veryonline_obliteratingsword_UnsafeUtil
 * Method:    free
 * Signature:  Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_neocities_a3441veryonline_obliteratingsword_UnsafeUtil_free
  (JNIEnv *, jint);

/*
 * Class:     org_neocities_a3441veryonline_obliteratingsword_UnsafeUtil
 * Method:    destroy
 * Signature:  Ljava/lang/Object;
 */
JNIEXPORT jboolean JNICALL Java_org_neocities_a3441veryonline_obliteratingsword_UnsafeUtil_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
